// swift-tools-version:6.2
// Auto-generated by scripts/xcframework.swift

import PackageDescription

let package = Package(
    name: "LiveKit",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15),
        .macCatalyst(.v14),
        .tvOS(.v17),
        .visionOS(.v26),
    ],
    products: [
        .library(name: "LiveKit", targets: ["LiveKit", "LiveKitWebRTC", "RustLiveKitUniFFI"]),
    ],
    targets: [
        .binaryTarget(
            name: "LiveKit",
            url: "https://github.com/livekit/client-sdk-swift-xcframework/releases/download/2.14.1/LiveKit.xcframework.zip",
            checksum: "902cc2dec08fe988a752441c78389f9148185539fb1cf00e7719201ca00ab514"
        ),
        .binaryTarget(
            name: "LiveKitWebRTC",
            url: "https://github.com/livekit/webrtc-xcframework/releases/download/144.7559.06/LiveKitWebRTC.xcframework.zip",
            checksum: "b1b0edf45d30a3ed92cc672392950bc7787fe08bad608e07c3f5eae8ec4c33f5"
        ),
        .binaryTarget(
            name: "RustLiveKitUniFFI",
            url: "https://github.com/livekit/livekit-uniffi-xcframework/releases/download/0.0.6/RustLiveKitUniFFI.xcframework.zip",
            checksum: "0d3f2ce159a224c728f8b131068d53bbf9b13d968cda0edc68a6a2290f2651ed"
        ),
    ]
)
