// swift-tools-version:6.2
// Auto-generated by scripts/xcframework.swift

import PackageDescription

let package = Package(
    name: "LiveKit",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15),
        .macCatalyst(.v14),
        .tvOS(.v17),
        .visionOS(.v26),
    ],
    products: [
        .library(name: "LiveKit", targets: ["LiveKit", "LiveKitWebRTC", "RustLiveKitUniFFI"]),
    ],
    targets: [
        .binaryTarget(
            name: "LiveKit",
            url: "https://github.com/livekit/client-sdk-swift-xcframework/releases/download/2.17.0/LiveKit.xcframework.zip",
            checksum: "7f175c55ddd6e2931f92c7ce0fc342e3ccd956bfc1061d3b9d17f8546e5222ba"
        ),
        .binaryTarget(
            name: "LiveKitWebRTC",
            url: "https://github.com/livekit/webrtc-xcframework/releases/download/150.7871.02/LiveKitWebRTC.xcframework.zip",
            checksum: "a523cd141d2aa6c3638d49fea1f72b0aafd28a8818c35fc240e08418da3d2fda"
        ),
        .binaryTarget(
            name: "RustLiveKitUniFFI",
            url: "https://github.com/livekit/livekit-uniffi-xcframework/releases/download/0.1.9/RustLiveKitUniFFI.xcframework.zip",
            checksum: "8db93e8ccd9f22263c39855808da48a4d6b5d620d8f6e43ab4501ede847b23eb"
        ),
    ]
)
